version: '3.4'

services:
  one-api:
    image: "my-one-api:latest"
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - /var/one-api/data:/data
      - /var/one-api/logs:/app/logs
    environment:
      - SQL_DSN=babaoapiroot:YirAzeJX.ZufMA98@tcp(172.16.2.1:3306)/oneapi # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://172.16.2.1
      - SESSION_SECRET=568742ee98f25cd89debd2c74ce08157  # 修改为随机字符串
      - TZ=Asia/Shanghai
      - DEBUG=true
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      network:
        ipv4_address: 172.16.2.2
networks:
  network:
    ipam:
      config:
        - subnet: 172.16.2.0/24